# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp for a bivariate density
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param n the number of between-sample random numbers
#' @param a the parameter of bivariate density
#' @param b the parameter of bivariate density
#' @return a random sample of size n
#' @examples
#' \dontrun{
#' set.seed(1211)
#' gibb_C<-gibbsC(120,15,1,1)
#' }
#' @export
gibbsC <- function(N, n, a, b) {
    .Call('_StatComp21093_gibbsC', PACKAGE = 'StatComp21093', N, n, a, b)
}

